### PR TITLE
Add script to bulk add issues to a github beta project

### PR DESCRIPTION
**Pull request by hayley-jean**
Adds all open issues in the specified repo to a Github Beta Project board.
If the issue already exists on the project board, the status will remain unchanged.

Note: This is a manual script and should not be run as part of a workflow.

### CODE REVIEW

**Review by oskardudycz — APPROVED** [review]

**Comment by oskardudycz** [comment]
@hayley-jean, don't we need to add `node_modules` to the repository to work fully?

**Comment by hayley-jean** [comment]
> @hayley-jean, don't we need to add `node_modules` to the repository to work fully?

We would only need that if this were to going to be run as part of a workflow. This is more a manual script to run once to populate boards such as the Triage board

**Comment by oskardudycz** [comment]
Ah, ok, I thought this would also be doable by manually triggering the workflow. Maybe that's something to consider?

**Comment by oskardudycz** [comment]
> We could update it to run as a workflow if we find that we need it at some point. The only reason I don't want to do that right now is because it updates all issues in a repository, which seems like something that should be run with care

Fine by me 👍

**Review by thefringeninja — APPROVED** [review]

**Pull request merged**
